import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 11,
    color: "#1a1a1a",
  },
  header: {
    textAlign: "center",
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: "#e5e7eb",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 10,
    color: "#6b7280",
  },
  scoreSection: {
    textAlign: "center",
    marginVertical: 24,
  },
  scoreNumber: {
    fontSize: 56,
    fontWeight: "bold",
    marginBottom: 2,
  },
  scoreLabel: {
    fontSize: 11,
    color: "#6b7280",
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    width: "46%",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 4,
    padding: 10,
    alignItems: "center",
  },
  statValue: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 9,
    color: "#6b7280",
  },
  breakdownSection: {
    marginBottom: 24,
  },
  breakdownTitle: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 10,
  },
  barRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  barLabel: {
    width: 110,
    fontSize: 10,
    color: "#374151",
  },
  barTrack: {
    flex: 1,
    height: 8,
    backgroundColor: "#f3f4f6",
    borderRadius: 4,
    marginHorizontal: 8,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 4,
  },
  barScore: {
    width: 40,
    textAlign: "right",
    fontSize: 10,
    color: "#6b7280",
  },
  disclaimer: {
    marginTop: 24,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    fontSize: 8,
    color: "#9ca3af",
    textAlign: "center",
  },
});

export function HealthCertificateDocument({
  score,
  breakdown,
  businessName,
  dateStr,
  totalInvoicedYear,
  collectionRatePct,
  avgPaymentTime,
  onTimePct,
  currency,
}: {
  score: number;
  breakdown: {
    label: string;
    score: number;
    maxScore: number;
    color: string;
  }[];
  businessName: string;
  dateStr: string;
  totalInvoicedYear: string;
  collectionRatePct: string;
  avgPaymentTime: string;
  onTimePct: string;
  currency: string;
}) {
  const scoreColor =
    score >= 70 ? "#22c55e" : score >= 40 ? "#f59e0b" : "#ef4444";

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Business Health Certificate</Text>
          <Text style={styles.subtitle}>
            {businessName} — Generated {dateStr}
          </Text>
        </View>

        <View style={styles.scoreSection}>
          <Text style={[styles.scoreNumber, { color: scoreColor }]}>
            {score}
          </Text>
          <Text style={styles.scoreLabel}>out of 100</Text>
        </View>

        <View style={styles.statsRow}>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{totalInvoicedYear}</Text>
            <Text style={styles.statLabel}>Total Invoiced (Year)</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{collectionRatePct}</Text>
            <Text style={styles.statLabel}>Collection Rate</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{avgPaymentTime}</Text>
            <Text style={styles.statLabel}>Avg Payment Time</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{onTimePct}</Text>
            <Text style={styles.statLabel}>On-Time %</Text>
          </View>
        </View>

        <View style={styles.breakdownSection}>
          <Text style={styles.breakdownTitle}>Score Breakdown</Text>
          {breakdown.map((item) => {
            const pct = (item.score / item.maxScore) * 100;
            return (
              <View key={item.label} style={styles.barRow}>
                <Text style={styles.barLabel}>{item.label}</Text>
                <View style={styles.barTrack}>
                  <View
                    style={[
                      styles.barFill,
                      { width: `${pct}%`, backgroundColor: item.color },
                    ]}
                  />
                </View>
                <Text style={styles.barScore}>
                  {item.score}/{item.maxScore}
                </Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.disclaimer}>
          Generated by Maroni. For reference purposes only. This score is not a
          credit score and is not shared with any third party.
        </Text>
      </Page>
    </Document>
  );
}
