import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { calculateBusinessHealthScore } from "@/lib/health-score";

export async function GET() {
  const session = await getServerSession(authOptions);

  if (!session?.user?.email) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const user = await prisma.user.findUnique({
    where: { email: session.user.email },
  });

  if (!user) {
    return NextResponse.json({ error: "User not found" }, { status: 404 });
  }

  if (user.plan !== "agency") {
    return NextResponse.json(
      { error: "Upgrade to Agency to download the Health Certificate." },
      { status: 403 },
    );
  }

  const health = await calculateBusinessHealthScore(user.id);
  const businessName = user.name ?? "Your Business";

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const scoreColor =
    health.score >= 70 ? "#22c55e" : health.score >= 40 ? "#f59e0b" : "#ef4444";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { margin: 40px; }
    body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #1a1a1a; line-height: 1.5; margin: 0; padding: 40px; }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 2px solid #e5e7eb; }
    .header h1 { font-size: 22px; margin: 0 0 4px; }
    .header p { font-size: 11px; color: #6b7280; margin: 0; }
    .score-section { text-align: center; margin: 32px 0; }
    .score-number { font-size: 64px; font-weight: bold; color: ${scoreColor}; }
    .stats-grid { display: flex; flex-wrap: wrap; gap: 16px; margin: 24px 0; }
    .stat-card { flex: 1; min-width: 140px; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center; }
    .stat-card .value { font-size: 20px; font-weight: 600; color: #1a1a1a; }
    .stat-card .label { font-size: 10px; color: #6b7280; margin-top: 4px; }
    .breakdown { margin: 24px 0; }
    .breakdown h3 { font-size: 14px; margin: 0 0 12px; }
    .bar-row { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
    .bar-label { width: 140px; font-size: 11px; color: #374151; }
    .bar-track { flex: 1; height: 8px; background: #f3f4f6; border-radius: 4px; overflow: hidden; }
    .bar-fill { height: 100%; border-radius: 4px; }
    .bar-score { width: 40px; text-align: right; font-size: 11px; color: #6b7280; }
    .disclaimer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #9ca3af; text-align: center; }
    .footer { margin-top: 16px; font-size: 9px; color: #9ca3af; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Business Health Certificate</h1>
    <p>${businessName} — Generated ${dateStr}</p>
  </div>

  <div class="score-section">
    <div class="score-number">${health.score}</div>
    <p style="font-size: 12px; color: #6b7280;">out of 100</p>
  </div>

  <div class="stats-grid">
    <div class="stat-card">
      <div class="value">${health.breakdown.collectionRate.score}/${health.breakdown.collectionRate.maxScore}</div>
      <div class="label">Collection Rate</div>
    </div>
    <div class="stat-card">
      <div class="value">${health.breakdown.avgDaysToPay.score}/${health.breakdown.avgDaysToPay.maxScore}</div>
      <div class="label">Payment Speed</div>
    </div>
    <div class="stat-card">
      <div class="value">${health.breakdown.revenueConsistency.score}/${health.breakdown.revenueConsistency.maxScore}</div>
      <div class="label">Revenue Stability</div>
    </div>
    <div class="stat-card">
      <div class="value">${health.breakdown.expenseRatio.score}/${health.breakdown.expenseRatio.maxScore}</div>
      <div class="label">Expense Control</div>
    </div>
    <div class="stat-card">
      <div class="value">${health.breakdown.taxReserve.score}/${health.breakdown.taxReserve.maxScore}</div>
      <div class="label">Tax Readiness</div>
    </div>
  </div>

  <div class="disclaimer">
    Generated by Maroni. For reference purposes only. This score is not a credit score
    and is not shared with any third party.
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="health-certificate-${now.toISOString().split("T")[0]}.html"`,
    },
  });
}
