interface PayslipEmailProps {
  businessName: string;
  contractorName: string;
  description: string;
  amount: string;
}

export function payslipEmail({ businessName, contractorName, description, amount }: PayslipEmailProps) {
  const subject = `Payslip from ${businessName}`;

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h2 style="color: #1a1a1a;">Payslip from ${businessName}</h2>
  <p style="color: #444; font-size: 15px; line-height: 1.6;">Hi ${contractorName},</p>
  <p style="color: #444; font-size: 15px; line-height: 1.6;">
    Please find attached your payslip for the payment of <strong>${amount}</strong>
    for: ${description}.
  </p>
  <p style="color: #444; font-size: 15px; line-height: 1.6;">
    This is a record of contractor payment. No tax has been withheld.
  </p>
  <p style="color: #444; font-size: 15px; line-height: 1.6;">Thanks,<br/>${businessName}</p>
  <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
  <p style="color: #999; font-size: 12px;">
    Generated by Maroni. This is not a tax document.
  </p>
</body>
</html>`.trim();

  return { subject, html };
}
