export interface TemplatePreview {
  key: string;
  label: string;
  trigger: string;
  subject: string;
  body: string;
  color: string;
  step: number;
}

export function getAllTemplatePreviews(): TemplatePreview[] {
  return [
    {
      key: "gentle_reminder",
      label: "Gentle Reminder",
      trigger: "3 days before due",
      subject: "Friendly reminder: Invoice is due soon",
      body: `Hi [Client Name],

This is just a friendly reminder that invoice #[Invoice Number] for [Amount] is due on [Due Date].

If you've already sent the payment, thank you! You can disregard this email.

If you have any questions, feel free to reach out.`,
      color: "#2563eb",
      step: 1,
    },
    {
      key: "due_today",
      label: "Due Today",
      trigger: "On due date",
      subject: "Invoice is due today",
      body: `Hi [Client Name],

This is a quick note to let you know that invoice #[Invoice Number] for [Amount] is due today ([Due Date]).

Please arrange payment at your earliest convenience.

Thank you for your prompt attention to this matter.`,
      color: "#d97706",
      step: 2,
    },
    {
      key: "overdue_notice",
      label: "Overdue Notice",
      trigger: "3 days after due",
      subject: "Overdue: Invoice payment needed",
      body: `Hi [Client Name],

Our records show that invoice #[Invoice Number] for [Amount] was due on [Due Date] and is now overdue.

If payment has already been sent, please disregard this notice. Otherwise, we'd appreciate it if you could settle this invoice as soon as possible.

Please let us know if there's any issue with the invoice.`,
      color: "#dc2626",
      step: 3,
    },
    {
      key: "firm_reminder",
      label: "Firm Reminder",
      trigger: "7 days after due",
      subject: "Urgent: Invoice remains unpaid",
      body: `Hi [Client Name],

We have not yet received payment for invoice #[Invoice Number] in the amount of [Amount], which was due on [Due Date].

This is now significantly overdue. Please arrange payment immediately or contact us to discuss the situation.

If we do not hear from you soon, we may need to take further action.`,
      color: "#b91c1c",
      step: 4,
    },
    {
      key: "final_notice",
      label: "Final Notice",
      trigger: "14 days after due",
      subject: "Final notice: Invoice - immediate payment required",
      body: `Hi [Client Name],

This is our final notice regarding invoice #[Invoice Number] for [Amount], which was due on [Due Date].

Despite our previous reminders, we have not received payment. Please settle this invoice immediately to avoid further escalation.

If payment is not received promptly, we reserve the right to pursue all available remedies.`,
      color: "#7f1d1d",
      step: 5,
    },
  ];
}

export function generateTemplatePdfHtml(templates: TemplatePreview[]): string {
  const cardsHtml = templates
    .map(
      (t) => `
    <div style="page-break-inside: avoid; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; margin-bottom: 20px; border-left: 4px solid ${t.color};">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
        <h3 style="margin: 0; font-size: 18px; font-weight: 600; color: #0f172a;">${t.label}</h3>
        <span style="font-size: 12px; font-weight: 600; color: ${t.color}; background: ${t.color}15; padding: 4px 10px; border-radius: 999px;">${t.trigger}</span>
      </div>
      <p style="margin: 0 0 12px; font-size: 14px; color: #64748b;"><strong>Subject:</strong> ${t.subject}</p>
      <pre style="margin: 0; font-family: inherit; font-size: 14px; line-height: 1.6; color: #334155; white-space: pre-wrap; background: #f8fafc; padding: 16px; border-radius: 8px;">${t.body}</pre>
    </div>
  `
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Invoice Reminder Email Templates - Invoice Nudger</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; color: #0f172a; background: #f8fafc; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 8px; }
    .subtitle { color: #64748b; margin-bottom: 32px; font-size: 14px; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Invoice Reminder Email Templates</h1>
  <p class="subtitle">5 escalating email templates from Invoice Nudger — from gentle reminder to final notice.</p>
  ${cardsHtml}
  <div class="footer">Generated by Invoice Nudger — invoice-nudger.com</div>
</body>
</html>`;
}
