"use client";

import { useState } from "react";
import toast from "react-hot-toast";

interface TemplateCardProps {
  label: string;
  trigger: string;
  subject: string;
  body: string;
  color: string;
  step: number;
}

export function TemplateCard({ label, trigger, subject, body, color, step }: TemplateCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = `Subject: ${subject}\n\n${body}`;
    await navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${label} - Maroni</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; color: #0f172a; padding: 40px; max-width: 600px; margin: 0 auto; }
    h1 { font-size: 20px; margin-bottom: 4px; }
    .trigger { font-size: 12px; font-weight: 600; color: ${color}; margin-bottom: 16px; }
    .subject { font-size: 14px; color: #64748b; margin-bottom: 16px; }
    .body { font-size: 14px; line-height: 1.6; white-space: pre-wrap; background: #f8fafc; padding: 20px; border-radius: 8px; border-left: 4px solid ${color}; }
    .footer { text-align: center; margin-top: 32px; color: #94a3b8; font-size: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${label}</h1>
  <p class="trigger">${trigger}</p>
  <p class="subject"><strong>Subject:</strong> ${subject}</p>
  <div class="body">${body}</div>
  <p class="footer">Generated by Maroni</p>
</body>
</html>`;
    const win = window.open("", "_blank");
    if (win) {
      win.document.write(html);
      win.document.close();
      win.focus();
      setTimeout(() => win.print(), 300);
    }
  };

  return (
    <div className="rounded-xl border border-border bg-surface p-6 shadow-sm transition hover:shadow-md">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <span
            className="flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold text-white"
            style={{ backgroundColor: color }}
          >
            {step}
          </span>
          <div>
            <h3 className="font-semibold text-foreground">{label}</h3>
            <span
              className="inline-block text-xs font-semibold"
              style={{ color }}
            >
              {trigger}
            </span>
          </div>
        </div>
      </div>

      <div className="mb-4 rounded-lg bg-surface-muted p-3">
        <p className="text-sm text-muted">
          <span className="font-medium text-foreground">Subject:</span>{" "}
          {subject}
        </p>
      </div>

      <pre className="mb-5 whitespace-pre-wrap rounded-lg bg-surface-muted p-4 text-sm leading-relaxed text-foreground">
        {body}
      </pre>

      <div className="flex gap-2">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 rounded-lg bg-surface px-3 py-2 text-sm font-medium text-foreground ring-1 ring-border transition hover:bg-surface-muted"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          {copied ? "Copied" : "Copy"}
        </button>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 rounded-lg bg-surface px-3 py-2 text-sm font-medium text-foreground ring-1 ring-border transition hover:bg-surface-muted"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          PDF
        </button>
      </div>
    </div>
  );
}
